---

- hosts: all
  become: true
  vars:
    install_pkgs:
      - mkpasswd
      - openscap-scanner
  tasks:
    - name: Install packages
      package:
        name: "{{ install_pkgs }}"
      state: latest
      enablerepo: epel
