
- hosts: all
  vars:
    allowed_ssh_networks:
      - 192.168.122.0/24
      - 10.10.10.0/24
    unnecessary_services:
      - autofs
      - debug.shell
      - ctrl-alt-del
    unnecessary_software:
      - tcpdump
      - nmap-ncat
      - wpa_supplicant
      - sendmail
      - nfs-utils
      - ypserv
      - rsh-server
      - telnet-server
      - gssproxy
      - iprutils
      - tuned
      - tftp
      - quagga

  tasks:
    - name: Add hardened SSH config
      copy:
        dest: /etc/ssh/sshd_config
        src: files/sshd_config
        owner: root
        group: root
        mode: 0600
      notify: Reload SSH

    - name: Add hardened SSH include config
      copy:
        dest: /etc/ssh/sshd_config.d/50-redhat.conf
        src: files/50-redhat.conf
        owner: root
        group: root
        mode: 0600
      notify: Reload SSH
    
    - name: Add hardened ciphers
      copy:
        dest: /etc/crypto-policies/back-ends/openssh.config
        src: files/openssh.config
        owner: root
        group: root
        mode: 0600
      notify: Reload SSH

    - name: Stop and disable firewalld on nodes
      service:
        name: firewalld
        state: stopped
        enabled: false

    - name: Remove undesirable packages
      package:
        name: "{{ unnecessary_software }}"
        state: absent

    - name: Stop and disable unnecessary services
      service:
        name: "{{ item }}"
        state: masked
        enabled: no
      with_items: "{{ unnecessary_services }}"
      ignore_errors: yes

  handlers:
    - name: Reload SSH
      service:
        name: sshd
        state: reloaded