---
- hosts: all
  become: yes
  tasks:
  - name: Update all packages
    yum:
      name: "*"
      state: latest
      update_cache: yes

  - name: Reboot if any packages were updated
    reboot:
      when: changed
