---

- hosts: all
  become: true
  tasks:

  - name: Update cache before upgrading all packages
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution in ["CentOS", "Fedora"]

