---

- hosts: all
  become: true
  tasks:

  - name: Update repo
    dnf:
      update_cache: yes
    when: ansible_distribution in ["CentOS", "Fedora"]

  - name: Upgrade all packages
    dnf:
      name: "*"
      state: latest
    when: ansible_distribution in ["CentOS", "Fedora"]

