apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: k0s-cluster
spec:
  k0s:
    version: null
    versionChannel: stable
    dynamicConfig: false
    config:
      spec:
        network:
          nodeLocalLoadBalancing:
            enabled: true
            type: EnvoyProxy
  hosts:
  - ssh:
      address: 192.168.3.10
      user: k0s
      port: 22
      keyPath: ~/.ssh/id_k0s
    role: controller
  - ssh:
      address: 192.168.3.20
      user: k0s
      port: 22
      keyPath: ~/.ssh/id_k0s
    role: controller
  - ssh:
      address: 192.168.3.30
      user: k0s
      port: 22
      keyPath: ~/.ssh/id_k0s
    role: controller
  - ssh:
      address: 192.168.3.11
      user: k0s
      port: 22
      keyPath: ~/.ssh/id_k0s
    role: worker
  - ssh:
      address: 192.168.3.12
      user: k0s
      port: 22
      keyPath: ~/.ssh/id_k0s
    role: worker
  - ssh:
      address: 192.168.3.21
      user: k0s
      port: 22
      keyPath: ~/.ssh/id_k0s
    role: worker
  - ssh:
      address: 192.168.3.22
      user: k0s
      port: 22
      keyPath: ~/.ssh/id_k0s
    role: worker
  - ssh:
      address: 192.168.3.31
      user: k0s
      port: 22
      keyPath: ~/.ssh/id_k0s
    role: worker
    