apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: k0s-cluster
spec:
  hosts:
  - ssh:
      address: 192.168.3.10
      user: k0s
      port: 22
      keyPath: ~/.ssh/id_k0s
    role: controller
  - ssh:
      address: 192.168.3.20
      user: k0s
      port: 22
      keyPath: ~/.ssh/id_k0s
    role: controller
  - ssh:
      address: 192.168.3.30
      user: k0s
      port: 22
      keyPath: ~/.ssh/id_k0s
    role: controller
  - ssh:
      address: 192.168.3.11
      user: k0s
      port: 22
      keyPath: ~/.ssh/id_k0s
    role: worker
  - ssh:
      address: 192.168.3.12
      user: k0s
      port: 22
      keyPath: ~/.ssh/id_k0s
    role: worker
  - ssh:
      address: 192.168.3.21
      user: k0s
      port: 22
      keyPath: ~/.ssh/id_k0s
    role: worker
  - ssh:
      address: 192.168.3.22
      user: k0s
      port: 22
      keyPath: ~/.ssh/id_k0s
    role: worker
  - ssh:
      address: 192.168.3.31
      user: k0s
      port: 22
      keyPath: ~/.ssh/id_k0s
    role: worker
  k0s:
    version: null
    versionChannel: stable
    dynamicConfig: false
    config:
      apiVersion: k0s.k0sproject.io/v1beta1
      kind: ClusterConfig
      spec:
        telemetry:
          enabled: false
        extensions:
          helm:
            repositories:
            - name: bitnami
              url: https://charts.bitnami.com/bitnami
            charts:
            - name: metallb
              chartname: bitnami/metallb
              version: "6.1.4"
              namespace: default
              values: |2
                configInline:
                  address-pools:
                  - name: generic-cluster-pool
                    protocol: layer2
                    addresses:
                    - 192.168.3.200-192.168.3.250