---

- hosts: all
  become: true
  
  vars:
    install_pkgs:
      - openscap-scanner
      - libguestfs-tools
      - wget

  tasks:
  - name: Install packages
    ansible.builtin.package:
      name: "{{ install_pkgs }}"
      state: latest
      update_cache: yes

