---

- hosts: all
  become: true
  
  vars:
    install_pkgs:
      - openscap-scanner
      - libguestfs-tools
      - wget
      - docker-ce
      - centos-release-gluster
      - glusterfs-server

  tasks:
  - name: Add repo docker-ce-stable
    ansible.builtin.yum_repository:
      name: docker-ce-stable
      description: Docker CE Stable - $basearch
      baseurl: https://download.docker.com/linux/centos/$releasever/$basearch/stable
      gpgcheck: yes
      gpgkey: https://download.docker.com/linux/centos/gpg

  - name: Ensure the crb repository is enabled
    community.general.dnf_config_manager:
      name: crb
      state: enabled

  - name: Install packages
    ansible.builtin.package:
      name: "{{ install_pkgs }}"
      state: latest
