---

- hosts: all
  become: true
  
  vars:
    install_pkgs:
      - openscap-scanner
      - libguestfs-tools
      - wget
  
  tasks:
    - name: Install packages
      package:
        name: "{{ install_pkgs }}"
      state: latest
      enablerepo: epel
