
- hosts: rhel
  become: true

  tasks:
  - name: Start and enable firewalld
    ansible.builtin.systemd:
      name: firewalld
      state: started
      enabled: yes

  - name: Add GlusterFS Service
    copy:
      dest: /etc/firewalld/services/glusterfs.xml
      src: files/glusterfs.xml
      owner: root
      group: root
      mode: 0644
    notify: reload_firewalld

  - name: Open GlusterFS Service
    ansible.posix.firewalld:
      service: glusterfs
      zone: public
      state: enabled
      permanent: yes
    notify: reload_firewalld

  - name: Open Docker Swarm Service
    ansible.posix.firewalld:
      service: docker-swarm
      zone: public
      state: enabled
      permanent: yes
    notify: reload_firewalld

  handlers:
    - name: reload_firewalld
      service:
        name: firewalld
        state: reloaded

