---
- hosts: rhel
  become: yes

  vars:
    fw_svc:
      - docker-swarm
      - glusterfs

  tasks:
  - name: Start and enable firewalld
    ansible.builtin.systemd:
      name: firewalld
      state: started
      enabled: yes

  - name: Add GlusterFS Service
    copy:
      dest: /etc/firewalld/services/glusterfs.xml
      src: files/glusterfs.xml
      owner: root
      group: root
      mode: 0644
    register: add_service

  - name: Restart firewalld if needed
    ansible.builtin.systemd:
      name: firewalld
      state: restarted
      enabled: yes
    when: add_service.changed

  - name: Open GlusterFS Service
    ansible.posix.firewalld:
      service: glusterfs
      zone: public
      state: enabled
      permanent: yes
    register: reload_firewalld

  - name: Restart firewalld if needed
    ansible.builtin.systemd:
      name: firewalld
      state: restarted
      enabled: yes
    when: reload_firewalld.changed
