---
- hosts: rhel
  become: yes

  vars:
    gluster_mount_dir: /mnt/gluster
    gluster_brick_dir: /srv/gluster/brick
    gluster_brick_name: gluster
    install_pkgs:
      - centos-release-gluster
      - glusterfs
      - glusterfs-server
      - glusterfs-geo-replication

  tasks:
    - name: enable crb repository #ensure ansible community.general is up-to-date
      community.general.dnf_config_manager:
        name: crb
        state: enabled

    - name: install packages
      ansible.builtin.package:
        name: "{{ install_pkgs }}"
        state: present
        update_cache: yes

    - name: ensure glusterd is enabled
      systemd:
        name: glusterd
        state: started
        enabled: yes

    - name: ensure gluster dirs exist
      file: "path={{ item }} state=directory mode=0775"
      with_items:
        - "{{ gluster_brick_dir }}"
        - "{{ gluster_mount_dir }}"

    - name: create a trusted storage pool
      gluster.gluster.gluster_peer:
        state: present
        nodes: "{{ groups.rhel }}"
      run_once: true

    - name: create gluster volume
      gluster.gluster.gluster_volume:
        state: present
        name: "{{ gluster_brick_name }}"
        bricks: "{{ gluster_brick_dir }}"
        replicas: 5
        cluster: "{{ groups.rhel }}"
        force: yes
      run_once: true

    - name: start gluster volume
      gluster.gluster.gluster_volume:
        state: started
        name: "{{ gluster_brick_name }}"
      run_once: true

    - name: ensure gluster volume is mounted
      mount:
        name: "{{ gluster_mount_dir }}"
        src: "{{ inventory_hostname_short }}:/{{ gluster_brick_name }}"
        fstype: glusterfs
        opts: "defaults,_netdev"
        state: mounted

#    - name: enable glusterfs repo
#      shell: |
#          dnf config-manager --enable crb
#          dnf install -y centos-release-gluster
